# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-13 09:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0004_auto_20181015_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('max_percentage_discount', models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='maximum percentage discount')),
                ('min_percentage_discount', models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='minimum percentage discount')),
                ('max_discount', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='maximum discount')),
                ('min_discount', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='minimum discount')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='admin')),
                ('admin_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_departments', to='auth.Group', verbose_name='admin group')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_department_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('default_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defalut_departments', to='auth.Group', verbose_name='default group')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_department_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.Department', verbose_name='department'),
        ),
    ]
