# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_department_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_departments', to=settings.AUTH_USER_MODEL, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='department',
            name='default_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_departments', to='auth.Group', verbose_name='default group'),
        ),
    ]
