# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 07:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_billinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='max_discount',
        ),
        migrations.RemoveField(
            model_name='department',
            name='min_discount',
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(blank=True, help_text='The unique user`s code', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
