# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 08:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181126_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='max_percentage_discount',
            field=models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='maximum percentage discount'),
        ),
        migrations.AlterField(
            model_name='department',
            name='min_percentage_discount',
            field=models.FloatField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='minimum percentage discount'),
        ),
    ]
