# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 14:23
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0056_auto_20180428_1423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(
                     auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(
                     auto_now=True, verbose_name='modified')),
                ('text',
                 models.TextField(
                     db_index=True,
                     validators=[django.core.validators.MinLengthValidator(2)],
                     verbose_name='text')),
                ('type',
                 models.CharField(
                     choices=[('message', 'message'), ('refusal', 'refusal')],
                     db_index=True,
                     default='message',
                     max_length=20,
                     verbose_name='type')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='contenttypes.ContentType')),
                ('created_by',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='billing_comment_created_by',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='created by')),
                ('modified_by',
                 models.ForeignKey(
                     blank=True,
                     editable=False,
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='billing_comment_modified_by',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='modified by')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
