# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'complete'), ('cancel', 'cancel')], db_index=True, max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('message', 'message'), ('refusal', 'refusal'), ('action', 'action')], db_index=True, default='message', max_length=20, verbose_name='type'),
        ),
    ]
