# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180507_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('cancel', 'cancel')], db_index=True, max_length=20, null=True, verbose_name='status'),
        ),
    ]
