# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180507_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('canceled', 'canceled')], db_index=True, max_length=20, null=True, verbose_name='status'),
        ),
    ]
