# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180508_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'permissions': (('change_related_comment', 'Can change related comments'),)},
        ),
    ]
