---
galaxy_info:
  author: "Chris Olstrom"
  categories:
    - development
  company: "TELUS digital"
  description: "Python is a programming language that lets you work quickly and integrate systems more effectively."
  license: MIT
  min_ansible_version: 1.9
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - utopic
        - xenial
