image: python:3.6.3

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - apt-get update; apt-get install -y gettext;
          - cp -n billing/settings_local.py.dist billing/settings_local.py
          - pip install -r requirements.txt
          - python manage.py migrate --no-input
          - python manage.py compilemessages
          - python -m pytest --pep8 --flakes --create-db
        services: 
          - redis
          - postgres
        
definitions: 
  services: 
    redis: 
      image: redis
    memcached: 
      image: memcached
    postgres: 
      image: postgres 
      environment: 
        POSTGRES_DB: billing 
        POSTGRES_USER: billing 
        POSTGRES_PASSWORD: billing
