# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('internal_id', models.CharField(db_index=True, max_length=100, verbose_name='internal_id')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='code')),
                ('end_date', models.CharField(db_index=True, max_length=100, verbose_name='end date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_fms_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_fms_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('internal_id', models.CharField(db_index=True, max_length=100, verbose_name='internal_id')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='code')),
                ('end_date', models.CharField(db_index=True, max_length=100, verbose_name='end date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_kpp_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fms_kpp_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='kpp',
            unique_together=set([('internal_id', 'name', 'code', 'end_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='fms',
            unique_together=set([('internal_id', 'name', 'code', 'end_date')]),
        ),
    ]
