# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fms',
            options={'verbose_name_plural': 'fms'},
        ),
        migrations.AlterModelOptions(
            name='kpp',
            options={'verbose_name_plural': 'kpp'},
        ),
        migrations.AlterUniqueTogether(
            name='fms',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='kpp',
            unique_together=set([]),
        ),
    ]
