# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_auto_20171019_1136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fms',
            unique_together=set([('internal_id', 'name', 'code', 'end_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='kpp',
            unique_together=set([('internal_id', 'name', 'code', 'end_date')]),
        ),
    ]
