# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_auto_20171019_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fms',
            name='end_date',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='kpp',
            name='end_date',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='end date'),
        ),
    ]
