# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0004_auto_20171019_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fms',
            name='end_date',
            field=models.CharField(db_index=True, default=1, max_length=100, verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpp',
            name='end_date',
            field=models.CharField(db_index=True, default='test', max_length=100, verbose_name='end date'),
            preserve_default=False,
        ),
    ]
