# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20170717_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(db_index=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('flat', 'Flat'), ('b&b', 'B&B'), ('vacation_rental', 'Vacation rental')], db_index=True, default='hotel', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.URLField(blank=True, db_index=True, null=True),
        ),
    ]
