# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170718_1559'),
        ('hotels', '0005_auto_20170717_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='clients.Client'),
            preserve_default=False,
        ),
    ]
