# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 10:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20170927_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0009_property_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='name')),
                ('description', models.TextField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='description')),
                ('rooms', models.PositiveIntegerField(db_index=True, help_text='max rooms', validators=[django.core.validators.MinValueValidator(1)], verbose_name='rooms')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clients.Client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_room_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_room_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.AddField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='hotels.Property', verbose_name='property'),
        ),
    ]
