# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20171023_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='client',
        ),
    ]
