# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-23 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_remove_room_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.Property', verbose_name='property'),
        ),
    ]
