# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_auto_20171102_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_checked',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is checked'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='country',
            name='is_checked',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is checked'),
        ),
        migrations.AddField(
            model_name='country',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_checked',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is checked'),
        ),
        migrations.AddField(
            model_name='region',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
    ]
