# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-05 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_auto_20180201_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='request_client',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='request_client',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='request_client',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
