# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20180205_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='request_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_city_request_client_by', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='country',
            name='request_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_country_request_client_by', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='region',
            name='request_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels_region_request_client_by', to='clients.Client'),
        ),
    ]
