# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-13 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_auto_20180206_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotels.City', verbose_name='city'),
        ),
    ]
