# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-15 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_auto_20180405_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_former',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is former'),
        ),
    ]
