# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_country_is_former'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'permissions': (('change_own', 'Can change only own entries'), ('change_department', 'Can change only department entries')), 'verbose_name_plural': 'properties'},
        ),
    ]
