# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 13:04
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_auto_20181128_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
