# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 11:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_auto_20170725_1201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0004_clientservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(db_index=True)),
                ('begin', models.DateTimeField(db_index=True, verbose_name='start date')),
                ('end', models.DateTimeField(db_index=True, verbose_name='end date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clients.Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_clientservice_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_clientservice_modified_by', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_services', to='finances.Service')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='clientservices',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientservices',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clientservices',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='clientservices',
            name='service',
        ),
        migrations.DeleteModel(
            name='ClientServices',
        ),
    ]
