# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20170725_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='start_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='begin',
            field=models.DateTimeField(db_index=True, verbose_name='begin date'),
        ),
    ]
