# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 12:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20170728_1258'),
        ('clients', '0007_auto_20170727_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hotels.Country', verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_client_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='installation',
            field=models.CharField(choices=[('not_installed', 'not installed'), ('process', 'process'), ('installed', 'installed')], db_index=True, default='not_installed', max_length=20, verbose_name='installation status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(code='invalid_login', message='Enter a valid login. This value may contain only lowercase letters, numbers, and "-" character.', regex='^[a-z0-9\\-]*$')], verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='client',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_client_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('not_confirmed', 'not confirmed'), ('active', 'active'), ('disabled', 'disabled'), ('archived', 'archived')], db_index=True, default='not_confirmed', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clients.Client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_clientservice_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_clientservice_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='quantity',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_services', to='finances.Service', verbose_name='service'),
        ),
    ]
