# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_auto_20170802_1209'),
        ('clients', '0010_auto_20170802_1129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together=set([('client', 'is_enabled', 'service')]),
        ),
    ]
