# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 13:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20170804_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
