# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20170804_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_services', to='hotels.Country', verbose_name='country'),
        ),
    ]
