# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20170804_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('active', 'active')], db_index=True, default='waiting', max_length=20, verbose_name='status'),
        ),
    ]
