# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_clientservice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('active', 'active')], db_index=True, default='waiting', max_length=20, verbose_name='status'),
        ),
    ]
