# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_order'),
        ('clients', '0016_auto_20170808_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='finances.Order', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('active', 'active')], db_index=True, default='active', max_length=20, verbose_name='status'),
        ),
    ]
