# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_order'),
        ('clients', '0017_auto_20170906_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservice',
            name='order',
        ),
        migrations.AddField(
            model_name='clientservice',
            name='orders',
            field=models.ManyToManyField(to='finances.Order', verbose_name='orders'),
        ),
    ]
