# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20170927_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, db_index=True, help_text='maxibooking url', null=True, verbose_name='url'),
        ),
    ]
