# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_client_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='orders',
            field=models.ManyToManyField(blank=True, to='finances.Order', verbose_name='orders'),
        ),
    ]
