# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_auto_20171124_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='rooms_limit',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='rooms limit'),
        ),
    ]
