# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20171124_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restrictions',
            options={'verbose_name_plural': 'restrictions'},
        ),
    ]
