# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_auto_20171124_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=50, null=True, verbose_name='phone'),
        ),
    ]
