# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 12:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_auto_20171102_1418'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0027_auto_20171127_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='name')),
                ('form', models.CharField(blank=True, choices=[('ooo', 'ooo'), ('oao', 'oao'), ('ip', 'ip'), ('zao', 'zao')], db_index=True, default='active', max_length=20, null=True, verbose_name='form')),
                ('ogrn', models.CharField(blank=True, db_index=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)], verbose_name='ogrn')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)], verbose_name='inn')),
                ('kpp', models.CharField(blank=True, db_index=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='kpp')),
                ('address', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='address')),
                ('postal_code', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('account_number', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('bank', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='bank')),
                ('swift', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='swift')),
                ('bik', models.CharField(blank=True, db_index=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='bik')),
                ('corr_account', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(30)], verbose_name='correspondent account')),
                ('boss_firstname', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='boss firstname')),
                ('boss_lastname', models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='boss lastname')),
                ('boss_patronymic', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='boss patronymic')),
                ('boss_operation_base', models.CharField(blank=True, choices=[('charter', 'charter'), ('proxy', 'proxy')], max_length=255, null=True, verbose_name='boss operation base')),
                ('proxy_number', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='proxy number')),
                ('proxy_date', models.DateTimeField(blank=True, null=True, verbose_name='proxy date')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.City', verbose_name='city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_company_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_company_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Region', verbose_name='region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
