# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20171127_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='bik',
        ),
        migrations.RemoveField(
            model_name='company',
            name='boss_firstname',
        ),
        migrations.RemoveField(
            model_name='company',
            name='boss_lastname',
        ),
        migrations.RemoveField(
            model_name='company',
            name='boss_operation_base',
        ),
        migrations.RemoveField(
            model_name='company',
            name='boss_patronymic',
        ),
        migrations.RemoveField(
            model_name='company',
            name='corr_account',
        ),
        migrations.RemoveField(
            model_name='company',
            name='form',
        ),
        migrations.RemoveField(
            model_name='company',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ogrn',
        ),
        migrations.RemoveField(
            model_name='company',
            name='proxy_date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='proxy_number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='swift',
        ),
    ]
