# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 08:31
from __future__ import unicode_literals

import annoying.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0030_auto_20171128_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRu',
            fields=[
                ('form', models.CharField(choices=[('ooo', 'ooo'), ('oao', 'oao'), ('ip', 'ip'), ('zao', 'zao')], db_index=True, default='active', max_length=20, verbose_name='form')),
                ('ogrn', models.CharField(db_index=True, max_length=13, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)], verbose_name='ogrn')),
                ('inn', models.CharField(db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)], verbose_name='inn')),
                ('kpp', models.CharField(db_index=True, max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)], verbose_name='kpp')),
                ('bik', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='bik')),
                ('corr_account', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(30)], verbose_name='correspondent account')),
                ('boss_firstname', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='boss firstname')),
                ('boss_lastname', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='boss lastname')),
                ('boss_patronymic', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='boss patronymic')),
                ('boss_operation_base', models.CharField(choices=[('charter', 'charter'), ('proxy', 'proxy')], max_length=255, verbose_name='boss operation base')),
                ('proxy_number', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='proxy number')),
                ('proxy_date', models.DateTimeField(verbose_name='proxy date')),
                ('company', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='world', serialize=False, to='clients.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyWorld',
            fields=[
                ('swift', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='swift')),
                ('company', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ru', serialize=False, to='clients.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
