# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 08:43
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_companyru_companyworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyru',
            name='company',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ru', serialize=False, to='clients.Company'),
        ),
        migrations.AlterField(
            model_name='companyworld',
            name='company',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='world', serialize=False, to='clients.Company'),
        ),
    ]
