# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 14:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_auto_20171102_1418'),
        ('clients', '0034_auto_20171128_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='address'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotels.City', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotels.Region', verbose_name='region'),
        ),
    ]
