# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_auto_20171201_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='clients.Client', verbose_name='client'),
        ),
    ]
