# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0037_auto_20180112_0835'),
        ('clients', '0038_auto_20171204_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='status',
            field=models.CharField(choices=[('archive', 'archive'), ('processing', 'processing'), ('active', 'active'), ('next', 'next')], db_index=True, default='active', max_length=20, verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together=set([('client', 'is_enabled', 'service', 'status')]),
        ),
    ]
