# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0037_auto_20180112_0835'),
        ('clients', '0039_auto_20180112_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together=set([('client', 'is_enabled', 'service', 'quantity')]),
        ),
    ]
