# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-15 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0040_auto_20180112_0848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientservice',
            unique_together=set([]),
        ),
    ]
