# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0042_clientservice_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyru',
            name='proxy_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='proxy date'),
        ),
        migrations.AlterField(
            model_name='companyru',
            name='proxy_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z', 32), code='invalid', message='Enter a valid integer.')], verbose_name='proxy number'),
        ),
    ]
