# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-01 07:51
from __future__ import unicode_literals

import clients.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0043_auto_20180122_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(code='invalid_login', message='Enter a valid login. This value may contain only lowercase letters, numbers, and "-" character.', regex='^[a-z0-9\\-]*$'), clients.validators.validate_client_login_restrictions], verbose_name='login'),
        ),
    ]
