# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-14 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0045_auto_20180213_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trial_activated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='trial activated'),
        ),
    ]
