# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0047_clientauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientauth',
            options={'ordering': ['auth_date'], 'verbose_name_plural': 'Client authentications'},
        ),
        migrations.AlterField(
            model_name='clientauth',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentications', to='clients.Client', verbose_name='client'),
        ),
    ]
