# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0048_auto_20180221_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientauth',
            options={'ordering': ['-auth_date'], 'verbose_name_plural': 'Client authentications'},
        ),
    ]
