# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0052_auto_20180406_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefusalReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='code')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_refusalreason_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_refusalreason_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name_plural': 'refusal reasons',
            },
        ),
        migrations.AlterModelOptions(
            name='salesstatus',
            options={'verbose_name_plural': 'sales statuses'},
        ),
        migrations.AlterField(
            model_name='salesstatus',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='code'),
        ),
    ]
