# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0053_auto_20180406_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='refusal_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.RefusalReason', verbose_name='refusal_reason'),
        ),
    ]
