# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0055_auto_20180409_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
