# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-18 11:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0056_auto_20180428_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyru',
            name='kpp',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z', 32), code='invalid', message='Enter a valid integer.')], verbose_name='kpp'),
        ),
        migrations.AlterField(
            model_name='companyru',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z', 32), code='invalid', message='Enter a valid integer.')], verbose_name='ogrn'),
        ),
    ]
