# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0057_auto_20180518_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(db_index=True, help_text='site url', unique=True, verbose_name='url')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='is enabled')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='site', serialize=False, to='clients.Client')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
