# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0058_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='website', serialize=False, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(db_index=True, help_text='The URL of client`s website must be unique among other clients.', unique=True, verbose_name='url'),
        ),
    ]
