# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-10 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('clients', '0059_auto_20180607_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={},
        ),
        migrations.RemoveField(
            model_name='website',
            name='created',
        ),
        migrations.RemoveField(
            model_name='website',
            name='modified',
        ),
    ]
