# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0061_auto_20180711_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='client',
        ),
        migrations.AddField(
            model_name='website',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
            preserve_default=False,
        ),
    ]
