# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-11 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0062_auto_20180711_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('url', models.URLField(db_index=True, help_text='The URL of client`s website must be unique among other clients.', unique=True, verbose_name='url')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='is enabled')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='clients.Client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_clientwebsite_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_clientwebsite_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='website',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='website',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
