# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-12 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0064_auto_20180712_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientru',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ru', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='clientru',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
