# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0068_companyworld_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyworld',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world', to='clients.Company'),
        ),
        migrations.AlterField(
            model_name='companyworld',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
