# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0069_auto_20180716_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyworld',
            options={'ordering': ['-created'], 'verbose_name': 'world', 'verbose_name_plural': 'world'},
        ),
    ]
