# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0072_companyru_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyru',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ru', to='clients.Company'),
        ),
        migrations.AlterField(
            model_name='companyru',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
