# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0073_auto_20180717_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyru',
            options={'ordering': ['-created'], 'verbose_name': 'ru', 'verbose_name_plural': 'ru'},
        ),
    ]
