# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-15 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0074_auto_20180717_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyru',
            name='ogrn',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(15), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z', 32), code='invalid', message='Enter a valid integer.')], verbose_name='ogrn'),
        ),
    ]
