# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-01 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0076_auto_20180911_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebsite',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is the website enabled?'),
        ),
    ]
