# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 11:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0077_auto_20181001_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
