# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 07:56
from __future__ import unicode_literals

import clients.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0078_client_manager_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='login',
            field=models.CharField(blank=True, db_index=True, error_messages={'unique': 'Client with this domain already exist.'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(code='invalid_login', message='Enter a valid domain. This value may contain only lowercase letters, numbers, and "-" character.', regex='^[a-z0-9\\-]*$'), clients.validators.validate_client_login_restrictions], verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='full name'),
        ),
    ]
