# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0082_auto_20181024_1057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set([]),
        ),
    ]
