# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0084_auto_20181120_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created']},
        ),
    ]
