# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0086_auto_20181128_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientservice',
            options={'ordering': ['-created'], 'permissions': (('change_own', 'Can change only own entries'), ('change_department', 'Can change only department entries'))},
        ),
    ]
