# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0087_auto_20181129_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created'], 'permissions': (('change_own', 'Can change only own entries'), ('change_department', 'Can change only department entries')), 'verbose_name_plural': 'companies'},
        ),
    ]
