# Generated by Django 2.2.3 on 2019-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0092_auto_20190716_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientwebsite',
            name='own_domain_name',
            field=models.BooleanField(db_index=True, default=False, help_text='Does the website use its own domain name?', verbose_name='own domain name?'),
        ),
    ]
