---
driver:
  # using docker to test
  name: docker
  privileged: true

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  # list ansible galaxy requirements from meta/main.yml

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  # suites found at /test/integration/$test-name
  - name: default
