
- name: Billing - copy settings
  copy:
    src: "{{billing.path}}billing/settings_local.py.dist"
    dest: "{{billing.path}}billing/settings_local.py"
    remote_src: yes
    force: no
  tags: billing  

- name: Billing - install nmp dependencies
  npm:
    path: "{{billing.path}}"
  tags: billing  

- name: Billing - makemigrations
  shell: python3.6 ./manage.py makemigrations
  args:
    chdir: "{{billing.path}}"
    executable: /usr/bin/fish
  tags: billing  

- name: Billing - migrate
  shell: python3.6 ./manage.py migrate
  args:
    chdir: "{{billing.path}}"
    executable: /usr/bin/fish
  tags: billing  

- name: Billing - compilemessages
  shell: python3.6 ./manage.py compilemessages
  args:
    chdir: "{{billing.path}}"
    executable: /usr/bin/fish
  tags: billing  

- name: Billing - load fixtures
  shell: python3.6 ./manage.py loaddata fixtures/tests/{{item}}.json
  with_items: "{{ billing.fixtures }}"
  args:
    chdir: "{{billing.path}}"
    executable: /usr/bin/fish
  tags: billing  
