# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iprange',
            options={'ordering': ['-modified', '-created'], 'verbose_name_plural': 'Ip ranges'},
        ),
        migrations.AlterField(
            model_name='iprange',
            name='end_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='end ip'),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='firewall.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='firewall.Rule', verbose_name='rule'),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='start_ip',
            field=models.GenericIPAddressField(db_index=True, verbose_name='start ip'),
        ),
    ]
