# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='url',
            field=models.CharField(db_index=True, default='.*', help_text='url regex pattern. Example: /admin/.*', max_length=255, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='entries',
            field=models.TextField(db_index=True, help_text='one ip, ip address range or domain per line.Example: 127.0.0.0/24', verbose_name='ip/domain list'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='entries',
            field=models.TextField(db_index=True, help_text='one ip, ip address range or domain per line.Example: 127.0.0.0/24', verbose_name='ip/domain list'),
        ),
    ]
