# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0002_auto_20180404_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprange',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='firewall.Group', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='firewall.Rule', verbose_name='rule'),
        ),
        migrations.AlterUniqueTogether(
            name='iprange',
            unique_together=set([]),
        ),
    ]
