# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import firewall.models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0003_auto_20180330_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='entries',
            field=firewall.models.EntriesField(db_index=True, help_text='one ip, ip address range or domain per line. Example: 127.0.0.0/24', verbose_name='ip/domain list'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='entries',
            field=firewall.models.EntriesField(blank=True, db_index=True, help_text='one ip, ip address range or domain per line. Example: 127.0.0.0/24', null=True, verbose_name='ip/domain list'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='groups',
            field=models.ManyToManyField(blank=True, to='firewall.Group', verbose_name='ip/domain groups'),
        ),
    ]
