# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0004_auto_20180330_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='url',
            field=models.CharField(db_index=True, help_text='Url regex pattern. Example: /admin/.*', max_length=255, verbose_name='url'),
        ),
    ]
