# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0005_auto_20180330_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_allow',
            field=models.BooleanField(db_index=True, default=True, help_text='Allow or deny?', verbose_name='is allow'),
        ),
    ]
