# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0006_rule_is_allow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='groups',
            field=models.ManyToManyField(blank=True, to='firewall.Group', verbose_name='ip groups'),
        ),
    ]
