# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-title']},
        ),
        migrations.AlterField(
            model_name='service',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('title', 'is_enabled')]),
        ),
    ]
