# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 12:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20170727_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_service_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_enabled',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is enabled'),
        ),
        migrations.AlterField(
            model_name='service',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_service_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AlterField(
            model_name='service',
            name='period',
            field=models.PositiveIntegerField(db_index=True, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='service',
            name='period_units',
            field=models.CharField(choices=[('day', 'day'), ('month', 'month'), ('year', 'year')], db_index=True, default='month', max_length=20, verbose_name='units of period'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
