# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 13:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20170731_0922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0005_auto_20170728_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='is enabled')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Country', verbose_name='country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_price_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_price_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='finances.Service', verbose_name='service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
