# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20170731_0922'),
        ('finances', '0006_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='price',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hotels.Country', verbose_name='country'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('price', 'service', 'country')]),
        ),
    ]
