# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20170731_0922'),
        ('finances', '0007_auto_20170731_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('service', 'country')]),
        ),
    ]
