# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_auto_20170731_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
