# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_remove_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('connection', 'connection'), ('rooms', 'rooms'), ('other', 'other')], db_index=True, default='other', max_length=20, verbose_name='type'),
        ),
    ]
