# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_service_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('title', 'is_enabled'), ('type', 'period', 'period_units')]),
        ),
    ]
