# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 08:49
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20170808_1452'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0013_service_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('paid', 'paid'), ('canceled', 'canceled')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('expired_date', models.DateTimeField(blank=True, db_index=True, verbose_name='expired date')),
                ('paid_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='paid date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.Client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_order_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
