# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20170906_0917'),
        ('finances', '0014_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_services',
            field=models.ManyToManyField(to='clients.ClientService', verbose_name='client services'),
        ),
    ]
