# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_order_client_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, db_index=True, verbose_name='note'),
        ),
    ]
