# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_auto_20170911_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='note'),
        ),
    ]
