# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_auto_20170913_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_services',
            field=models.ManyToManyField(blank=True, to='clients.ClientService', verbose_name='client services'),
        ),
    ]
