# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0021_auto_20170913_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, db_index=True, help_text='Clear to regenerate note', null=True, verbose_name='note'),
        ),
    ]
