# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_auto_20170926_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='disable_date',
        ),
    ]
