# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 12:25
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0025_auto_20170927_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default=Decimal('0.0'), max_digits=20, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble')], default='EUR', editable=False, max_length=3),
        ),
    ]
