# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_auto_20171023_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('stripe', 'stripe'), ('rbk', 'rbk'), ('bill', 'bill')], db_index=True, max_length=20, null=True, verbose_name='payment system'),
        ),
    ]
