# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 09:31
from __future__ import unicode_literals

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models

from finances.models import ServiceCategory


def create_category(*args):
    if not ServiceCategory.objects.first():
        ServiceCategory.objects.create(title="Migration category")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0033_service_default_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(
                     auto_now=True, verbose_name='modified')),
                ('title', models.CharField(
                    max_length=255, verbose_name='title')),
                ('description', models.TextField(
                    blank=True, null=True, verbose_name='description')),
                ('created_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='finances_servicecategory_created_by',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='created by')),
                ('modified_by', models.ForeignKey(
                    blank=True,
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='finances_servicecategory_modified_by',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_en',
            field=models.TextField(
                blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_ru',
            field=models.TextField(
                blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_en',
            field=models.CharField(
                max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='title_ru',
            field=models.CharField(
                max_length=255, null=True, verbose_name='title'),
        ),
        migrations.RunPython(create_category),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='services',
                to='finances.ServiceCategory',
                verbose_name='category'),
            preserve_default=False,
        ),
    ]
