# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0036_auto_20171215_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['title'], 'verbose_name_plural': 'service categories'},
        ),
    ]
