# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0039_auto_20180117_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='period_from',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='from'),
        ),
        migrations.AddField(
            model_name='price',
            name='period_to',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='from'),
        ),
    ]
