# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_auto_20180213_0808'),
        ('finances', '0040_auto_20180313_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='period_to',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='to'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('service', 'country', 'period_from', 'period_to')]),
        ),
    ]
