# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0041_auto_20180313_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['country', 'period_from', 'period_to', 'price']},
        ),
        migrations.AddField(
            model_name='price',
            name='for_unit',
            field=models.BooleanField(db_index=True, default=True, verbose_name='for unit'),
        ),
    ]
