# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0046_auto_20180405_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='default_rooms',
        ),
    ]
