# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0047_remove_service_default_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-modified', '-created'), 'permissions': (('list_manager', 'Can see assigned entries'),)},
        ),
    ]
