# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-27 10:52
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0074_auto_20180717_1109'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0049_auto_20180724_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('enabled', 'enabled'), ('canceled', 'canceled')], db_index=True, default='enabled', max_length=20, verbose_name='status')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(blank=True, db_index=True, decimal_places=2, default=Decimal('0.0'), max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('period', models.PositiveIntegerField(db_index=True, verbose_name='period')),
                ('merchant', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='merchant')),
                ('customer', models.CharField(db_index=True, max_length=255, verbose_name='merchant')),
                ('subscription', models.CharField(db_index=True, max_length=255, verbose_name='subscription')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='clients.Client', verbose_name='client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_subscription_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_subscription_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
