# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_auto_20180405_0943'),
        ('finances', '0051_auto_20180814_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='hotels.Country', verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.CharField(db_index=True, max_length=255, verbose_name='customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.PositiveIntegerField(db_index=True, help_text='the billing period in months', verbose_name='period'),
        ),
    ]
