# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0052_auto_20180814_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('stripe', 'stripe'), ('braintree', 'braintree'), ('braintree-subscription', 'braintree-subscription'), ('paypal', 'paypal'), ('rbk', 'rbk'), ('sberbank', 'sberbank'), ('bill', 'bill')], db_index=True, max_length=30, null=True, verbose_name='payment system'),
        ),
    ]
