# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 07:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20181126_0755'),
        ('finances', '0053_auto_20181015_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='begin date')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='end date')),
                ('number_of_uses', models.PositiveIntegerField(db_index=True, default=1, help_text='To how many orders per user can this discount be applied', verbose_name='number of uses')),
                ('percentage_discount', models.PositiveIntegerField(db_index=True, verbose_name='percentage discount')),
                ('code', models.CharField(blank=True, help_text='The unique code of the discount', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_discount_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='users.Department', verbose_name='department')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_discount_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
