# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 12:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0054_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'permissions': (('change_own_discount', 'Can change only own discounts'), ('change_department_discount', 'Can change only department discounts'))},
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage_discount',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='percentage discount'),
        ),
    ]
