# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0055_auto_20181206_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='user',
        ),
        migrations.AddField(
            model_name='discount',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
    ]
