# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0056_auto_20181212_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'permissions': (('change_own_discount', 'Can change only own discounts'), ('delete_any_discount', 'Can delete any discounts'), ('change_department_discount', 'Can change only department discounts'))},
        ),
    ]
