# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0059_auto_20181213_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
    ]
