# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 09:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import finances.validators


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0060_auto_20181213_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, help_text='The unique code of the discount', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), finances.validators.validate_code]),
        ),
    ]
