# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 09:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import finances.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0088_auto_20181129_1206'),
        ('users', '0011_auto_20181217_0908'),
        ('finances', '0061_auto_20181217_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='begin date')),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='end date')),
                ('number_of_uses', models.PositiveIntegerField(db_index=True, default=1, help_text='To how many orders per user can this discount be applied', verbose_name='number of uses')),
                ('percentage_discount', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='percentage discount')),
                ('code', models.CharField(blank=True, help_text='The unique code of the discount', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), finances.validators.validate_code])),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='clients.Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_clientdiscount_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_clientdiscount_discounts', to='users.Department', verbose_name='department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_clientdiscount_discounts', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_clientdiscount_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='discount',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_discount_discounts', to='users.Department', verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances_discount_discounts', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
    ]
