# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0062_auto_20181217_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdiscount',
            name='original_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_discount', to='finances.Discount'),
        ),
    ]
