# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0063_clientdiscount_original_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdiscount',
            name='usage_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='The number of times the discount has already been applied'),
        ),
    ]
