# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 12:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0065_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default=Decimal('0'), help_text='Set zero to recalculate price', max_digits=20, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=djmoney.models.fields.MoneyField(db_index=True, decimal_places=2, default=Decimal('0.0'), max_digits=20, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, db_index=True, decimal_places=2, default=Decimal('0.0'), max_digits=20, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
    ]
