# Generated by Django 2.2.3 on 2019-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0067_auto_20190211_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('stripe', 'stripe'), ('braintree', 'braintree'), ('braintree-subscription', 'braintree-subscription'), ('paypal', 'paypal'), ('rbk', 'rbk'), ('sberbank', 'sberbank'), ('sberbank-rest', 'sberbank-rest'), ('bill', 'bill')], db_index=True, max_length=30, null=True, verbose_name='payment system'),
        ),
    ]
